name: my_product
description: VIP Product App

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  image_picker: ^1.0.4
  mobile_scanner: ^3.5.2
  pdf: ^3.10.4
  printing: ^5.11.0
  provider: ^6.0.5

flutter:
  uses-material-design: true
